[package]
name = "hako"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Hako language transpiler - DSL for bare-metal programming"
repository = "https://github.com/levementesalgado/Hako"
readme = "README.md"
keywords = ["dsl", "bare-metal", "kernel", "transpiler", "systems"]
categories = ["command-line-utilities", "development-tools"]
exclude = ["/examples", "/tests", "/benches", "/target", "/.github"]

[lib]
name = "hako"
path = "src/lib.rs"

[[bin]]
name = "hako"
path = "src/main.rs"
