use std::path::PathBuf;
use std::process::Command;

fn main() {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    // Assemble boot code
    let asm_files = ["boot.asm", "interrupts.asm"];

    for asm in &asm_files {
        let src = format!("src/arch/i686/{}", asm);
        let obj_name = format!("{}.o", asm.replace('.', "_"));
        let obj = out_dir.join(&obj_name);
        let status = Command::new("as")
            .args(&["--32", "-o", &obj.to_string_lossy(), &src])
            .status()
            .expect(&format!("failed to assemble {}", src));
        assert!(status.success(), "assembly failed: {}", src);
        println!("cargo:rustc-link-arg={}", obj.display());
    }

    // Build mizu-init with user-space target
    let workspace_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap())
        .parent().unwrap().to_path_buf();
    let target_spec = workspace_dir.join("mizu-init/i686-mizu-user.json");
    let init_out = out_dir.join("mizu-init");
    let status = Command::new("cargo")
        .args(&[
            "+nightly", "build",
            "-Zbuild-std=core,compiler_builtins",
            "-Zbuild-std-features=compiler-builtins-mem",
            "-Zjson-target-spec",
            &format!("--target={}", target_spec.to_string_lossy()),
            "-p", "mizu-init",
            &format!("--target-dir={}", init_out.to_string_lossy()),
        ])
        .current_dir(&workspace_dir)
        .status()
        .expect("failed to build mizu-init");
    assert!(status.success(), "mizu-init build failed");

    // Copy init.elf to a known location
    let target_name = target_spec.file_stem().unwrap().to_str().unwrap();
    let profile = std::env::var("PROFILE").unwrap_or_else(|_| "debug".to_string());
    let init_elf_src = init_out.join(format!("{}/{}/mizu-init", target_name, profile));
    let init_elf_dst = out_dir.join("init.elf");
    std::fs::copy(&init_elf_src, &init_elf_dst).expect("failed to copy init.elf");

    // Build initramfs tar with hello.elf and init.elf
    let tar_dst = out_dir.join("initramfs.tar");
    let tar_status = Command::new("tar")
        .args(&["cf", &tar_dst.to_string_lossy(),
            "-C", &workspace_dir.join("mizu-kernel").to_string_lossy(),
            "hello.elf",
            "-C", &workspace_dir.join("mizu-kernel").to_string_lossy(),
            "bash.elf",
            "-C", &out_dir.to_string_lossy(),
            "init.elf",
        ])
        .status()
        .expect("failed to create initramfs tar");
    assert!(tar_status.success(), "tar creation failed");

    let initramfs_obj = out_dir.join("initramfs.o");
    let status = Command::new("ld")
        .current_dir(&out_dir)
        .args(&["-r", "-m", "elf_i386", "-b", "binary", "-o", "initramfs.o", "initramfs.tar"])
        .status()
        .expect("failed to create initramfs object");
    assert!(status.success(), "initramfs object failed");
    println!("cargo:rustc-link-arg={}", initramfs_obj.display());

    // Linker script
    let link_ld = out_dir.join("link.ld");
    std::fs::write(&link_ld, include_str!("src/arch/i686/link.ld"))
        .expect("failed to write link.ld");
    println!("cargo:rustc-link-arg=-T{}", link_ld.display());

    // Transpile Hako files
    let hako_src_dir = PathBuf::from("src/hako");
    if hako_src_dir.exists() {
        let hako_gen_dir = out_dir.join("hako_gen");
        std::fs::create_dir_all(&hako_gen_dir).ok();

        let mut mod_rs = String::from("// Generated by Hako transpiler\n");
        mod_rs.push_str("// do not edit\n\n");

        // Emit stdlib once
        mod_rs.push_str("pub mod hako_stdlib {\n");
        mod_rs.push_str(hako::stdlib::STDLIB);
        mod_rs.push_str("\n}\n\n");

        // Collect .hako files sorted for deterministic output
        let mut hako_files: Vec<_> = std::fs::read_dir(&hako_src_dir)
            .expect("read hako dir")
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().map_or(false, |ext| ext == "hako"))
            .collect();
        hako_files.sort_by_key(|e| e.path());

        for entry in &hako_files {
            let path = entry.path();
            let input = std::fs::read_to_string(&path)
                .expect(&format!("read {}", path.display()));

            match hako::transpile_string(&input) {
                Ok((code, boxes, impls)) => {
                    eprintln!("hako: {} → {} ({} boxes, {} impls)",
                        path.display(), "hako_gen", boxes, impls);
                    mod_rs.push_str(&code);
                    mod_rs.push_str("\n");
                }
                Err(e) => panic!("hako transpile error: {}", e),
            }

            println!("cargo:rerun-if-changed={}", path.display());
        }

        // Rename Hako's 'process' module to avoid conflict with our Rust process module
        let mod_rs = mod_rs.replace("pub mod process {", "pub mod hako_process {");
        let mod_rs = mod_rs.replace("process::run();", "hako_process::run();");

        let mod_path = hako_gen_dir.join("mod.rs");
        std::fs::write(&mod_path, &mod_rs).expect("write hako mod.rs");
    }

    println!("cargo:rerun-if-changed=src/arch/i686/link.ld");
    println!("cargo:rerun-if-changed=src/arch/i686/boot.asm");
    println!("cargo:rerun-if-changed=src/arch/i686/interrupts.asm");
    println!("cargo:rerun-if-changed=../mizu-init/src/");
    println!("cargo:rerun-if-changed=../mizu-init/Cargo.toml");
    println!("cargo:rerun-if-changed=src/hako/");
}

