use hako::codegen::Codegen;
use hako::parser::Parser;

// ===== Codegen Tests =====

fn transpile(input: &str) -> String {
    let mut p = Parser::new(input);
    let program = p.parse().unwrap();
    let mut cg = Codegen::new();
    cg.generate_full(&program)
}

#[test]
fn test_codegen_header() {
    let input = "box test { }";
    let output = transpile(input);
    assert!(output.contains("// Generated by Hako transpiler"));
}

#[test]
fn test_codegen_single_box() {
    let input = r#"
box serial {
    COM1 = 0x3F8
}
"#;
    let output = transpile(input);
    assert!(output.contains("pub mod serial {"));
    assert!(output.contains("pub const COM1: u32 = 0x3F8;"));
    assert!(output.contains("}"));
}

#[test]
fn test_codegen_box_with_extends() {
    let input = r#"
box vga::video {
    BASE = 0xB8000
}
"#;
    let output = transpile(input);
    assert!(output.contains("pub mod vga_video {"));
}

#[test]
fn test_codegen_auto_mode_function() {
    let input = r#"
box serial {
    COM1 = 0x3F8
    config => default
}
"#;
    let output = transpile(input);
    assert!(output.contains("pub fn config()"));
    assert!(output.contains("crate::hako_stdlib::serial_config("));
    assert!(output.contains("COM1"));
}

#[test]
fn test_codegen_auto_mode_with_params() {
    let input = r#"
box serial {
    COM1 = 0x3F8
    write_byte(b) => default
}
"#;
    let output = transpile(input);
    assert!(output.contains("pub fn write_byte(b: u32)"));
    assert!(output.contains("crate::hako_stdlib::serial_write_byte(b, COM1)"));
}

#[test]
fn test_codegen_block_function() {
    let input = r#"
box test {
    run {
        x = 10
        y = 20
    }
}
"#;
    let output = transpile(input);
    assert!(output.contains("pub fn run()"));
    assert!(output.contains("x = 10;"));
    assert!(output.contains("y = 20;"));
}

#[test]
fn test_codegen_raw_function() {
    let input = r#"
box test {
    asm_test raw {
        out(al, x)
        "mov eax, 1"
        in(eax, result)
    }
}
"#;
    let output = transpile(input);
    assert!(output.contains("pub fn asm_test()"));
    assert!(output.contains("let mut __out_x: u8;"));
    assert!(output.contains("core::arch::asm!("));
    assert!(output.contains("\"mov eax, 1\""));
    assert!(output.contains("in(\"eax\") result"));
    assert!(output.contains("out(\"al\") __out_x"));
    assert!(output.contains("let x = __out_x;"));
}

#[test]
fn test_codegen_flow() {
    let input = r#"
flow default {
    serial
    vga
}
"#;
    let output = transpile(input);
    assert!(output.contains("pub fn flow_default()"));
    assert!(output.contains("serial::run();"));
    assert!(output.contains("vga::run();"));
}

#[test]
fn test_codegen_if_statement() {
    let input = r#"
box test {
    check {
        if x > 0 => {
            y = 1
        } else {
            y = 0
        }
    }
}
"#;
    let output = transpile(input);
    assert!(output.contains("if x > 0 {"));
    assert!(output.contains("y = 1;"));
    assert!(output.contains("} else {"));
    assert!(output.contains("y = 0;"));
}

#[test]
fn test_codegen_loop_statement() {
    let input = r#"
box test {
    run {
        loop {
            x = x + 1
        }
    }
}
"#;
    let output = transpile(input);
    assert!(output.contains("loop {"));
    assert!(output.contains("x = x + 1;"));
}

#[test]
fn test_codegen_for_statement() {
    let input = r#"
box test {
    run {
        for i in 0..10 {
            x = i
        }
    }
}
"#;
    let output = transpile(input);
    assert!(output.contains("for i in 0..10 {"));
    assert!(output.contains("x = i;"));
}

#[test]
fn test_codegen_break_statement() {
    let input = r#"
box test {
    run {
        break
    }
}
"#;
    let output = transpile(input);
    assert!(output.contains("break;"));
}

#[test]
fn test_codegen_multiple_boxes() {
    let input = r#"
box serial {
    COM1 = 0x3F8
}

box vga {
    BASE = 0xB8000
}
"#;
    let output = transpile(input);
    assert!(output.contains("pub mod serial {"));
    assert!(output.contains("pub mod vga {"));
}

#[test]
fn test_codegen_reg_type() {
    // Test register type mapping
    let input = r#"
box test {
    asm_test raw {
        out(al, x)
        "mov al, 0"
    }
}
"#;
    let output = transpile(input);
    assert!(output.contains("let mut __out_x: u8;")); // al -> u8
}

#[test]
fn test_codegen_reg_type_u16() {
    let input = r#"
box test {
    asm_test raw {
        out(ax, x)
        "mov ax, 0"
    }
}
"#;
    let output = transpile(input);
    assert!(output.contains("let mut __out_x: u16;")); // ax -> u16
}

#[test]
fn test_codegen_reg_type_u32() {
    let input = r#"
box test {
    asm_test raw {
        out(eax, x)
        "mov eax, 0"
    }
}
"#;
    let output = transpile(input);
    assert!(output.contains("let mut __out_x: u32;")); // eax -> u32
}

#[test]
fn test_codegen_stdlib_mapping() {
    // Test all stdlib function mappings
    let input = r#"
box serial {
    COM1 = 0x3F8
    config => default
    write_byte(b) => default
    read_byte => default
}

box vga {
    put_char(c) => default
    write(s) => default
    clear => default
    scroll => default
    set_cursor(pos) => default
}

box io {
    outb(port, val) => default
    inb(port) => default
}

box kbd {
    init => default
}
"#;
    let output = transpile(input);
    assert!(output.contains("serial_config("));
    assert!(output.contains("serial_write_byte("));
    assert!(output.contains("serial_read_byte("));
    assert!(output.contains("vga_put_char("));
    assert!(output.contains("vga_write_str("));
    assert!(output.contains("vga_clear("));
    assert!(output.contains("vga_scroll("));
    assert!(output.contains("vga_set_cursor("));
    assert!(output.contains("port_outb("));
    assert!(output.contains("port_inb("));
    assert!(output.contains("keyboard_init("));
}

#[test]
fn test_codegen_empty_box() {
    let input = r#"
box empty {
}
"#;
    let output = transpile(input);
    assert!(output.contains("pub mod empty {"));
    assert!(output.contains("use super::*;"));
    assert!(output.contains("}"));
}

#[test]
fn test_codegen_complex_program() {
    let input = r#"
box serial {
    COM1 = 0x3F8
    config => default
    write_byte(b) => default
}

box vga {
    BASE = 0xB8000
    clear => default
    write(s) => default
}

flow default {
    serial
    vga
}
"#;
    let output = transpile(input);
    assert!(output.contains("pub mod serial {"));
    assert!(output.contains("pub mod vga {"));
    assert!(output.contains("pub fn flow_default()"));
    assert!(output.contains("serial::run();"));
    assert!(output.contains("vga::run();"));
}
