use hako::transpile_file;
use hako::transpile_string;
use std::fs;
use std::path::Path;

// ===== Integration Tests =====

#[test]
fn test_transpile_string_returns_counts() {
    let input = r#"
box serial {
    COM1 = 0x3F8
}

flow default {
    serial
}
"#;
    let (code, boxes, flows) = transpile_string(input).unwrap();
    assert_eq!(boxes, 1);
    assert_eq!(flows, 1);
    assert!(!code.is_empty());
}

#[test]
fn test_transpile_string_produces_valid_rust() {
    let input = r#"
box serial {
    COM1 = 0x3F8
    config => default
    write_byte(b) => default
}

box vga {
    BASE = 0xB8000
    clear => default
    write(s) => default
}

flow default {
    serial
    vga
}
"#;
    let (code, _, _) = transpile_string(input).unwrap();

    // Check that the output contains valid Rust syntax
    assert!(code.contains("pub mod serial {"));
    assert!(code.contains("pub mod vga {"));
    assert!(code.contains("pub const COM1: u32 = 0x3F8;"));
    assert!(code.contains("pub const BASE: u32 = 0xB8000;"));
    assert!(code.contains("pub fn config()"));
    assert!(code.contains("pub fn write_byte(b: u32)"));
    assert!(code.contains("pub fn clear()"));
    assert!(code.contains("pub fn write(s: &str)"));
    assert!(code.contains("pub fn flow_default()"));
    assert!(code.contains("serial::run();"));
    assert!(code.contains("vga::run();"));
}

#[test]
fn test_transpile_file() {
    let input_path = Path::new("/tmp/test_input.hako");
    let output_path = Path::new("/tmp/test_output.rs");

    let input = r#"
box test {
    VALUE = 42
    run {
        x = VALUE
    }
}
"#;

    fs::write(input_path, input).unwrap();
    let result = transpile_file(input_path, output_path);
    assert!(result.is_ok());

    let (boxes, flows) = result.unwrap();
    assert_eq!(boxes, 1);
    assert_eq!(flows, 0);

    let output = fs::read_to_string(output_path).unwrap();
    assert!(output.contains("pub const VALUE: u32 = 42;"));
    assert!(output.contains("pub fn run()"));

    // Cleanup
    let _ = fs::remove_file(input_path);
    let _ = fs::remove_file(output_path);
}

#[test]
fn test_transpile_empty_input() {
    let (code, boxes, flows) = transpile_string("").unwrap();
    assert_eq!(boxes, 0);
    assert_eq!(flows, 0);
    assert!(code.contains("// Generated by Hako transpiler"));
}

#[test]
fn test_transpile_comments_only() {
    let input = r#"
// Just a comment
/* Another comment */
"#;
    let (code, boxes, flows) = transpile_string(input).unwrap();
    assert_eq!(boxes, 0);
    assert_eq!(flows, 0);
}

#[test]
fn test_transpile_preserves_constants() {
    let input = r#"
box serial {
    COM1 = 0x3F8
    COM2 = 0x2F8
    BAUD_RATE = 115200
}
"#;
    let (code, _, _) = transpile_string(input).unwrap();
    assert!(code.contains("pub const COM1: u32 = 0x3F8;"));
    assert!(code.contains("pub const COM2: u32 = 0x2F8;"));
    assert!(code.contains("pub const BAUD_RATE: u32 = 115200;"));
}

#[test]
fn test_transpile_auto_mode_injects_constants() {
    let input = r#"
box serial {
    COM1 = 0x3F8
    config => default
    write_byte(b) => default
}
"#;
    let (code, _, _) = transpile_string(input).unwrap();
    // Auto mode should inject COM1 as extra argument
    assert!(code.contains("crate::hako_stdlib::serial_config(COM1)"));
    assert!(code.contains("crate::hako_stdlib::serial_write_byte(b, COM1)"));
}

#[test]
fn test_transpile_multiple_flows() {
    let input = r#"
box serial { COM1 = 0x3F8 }
box vga { BASE = 0xB8000 }

flow init {
    serial
    vga
}

flow run {
    vga
    serial
}
"#;
    let (code, _, flows) = transpile_string(input).unwrap();
    assert_eq!(flows, 2);
    assert!(code.contains("pub fn flow_init()"));
    assert!(code.contains("pub fn flow_run()"));
}

#[test]
fn test_transpile_raw_assembly() {
    let input = r#"
box test {
    halt raw {
        out(al, x)
        "hlt"
    }
}
"#;
    let (code, _, _) = transpile_string(input).unwrap();
    assert!(code.contains("core::arch::asm!("));
    assert!(code.contains("\"hlt\""));
    assert!(code.contains("out(\"al\")"));
}

#[test]
fn test_transpile_complex_control_flow() {
    let input = r#"
box test {
    run {
        for i in 0..10 {
            if i > 5 => {
                x = i
            } else {
                x = i
            }
            if x == 10 => {
                break
            }
        }
        loop {
            y = y + 1
            if y > 100 => {
                break
            }
        }
    }
}
"#;
    let (code, _, _) = transpile_string(input).unwrap();
    assert!(code.contains("for i in 0..10 {"));
    assert!(code.contains("if i > 5 {"));
    assert!(code.contains("} else {"));
    assert!(code.contains("break;"));
    assert!(code.contains("loop {"));
    assert!(code.contains("if y > 100 {"));
}

#[test]
fn test_transpile_error_invalid_syntax() {
    let input = r#"
box serial {
}
box
"#;
    let result = transpile_string(input);
    assert!(result.is_err());
}

#[test]
fn test_transpile_real_world_example() {
    // A more realistic example of what Hako would be used for
    let input = r#"
box serial {
    COM1 = 0x3F8
    config => default
    write_byte(b) => default
    read_byte => default
}

box vga {
    BASE = 0xB8000
    clear => default
    write(s) => default
    put_char(c) => default
}

box keyboard {
    init => default
}

flow boot {
    serial
    vga
    keyboard
}

flow default {
    serial
    vga
}
"#;
    let (code, boxes, flows) = transpile_string(input).unwrap();
    assert_eq!(boxes, 3);
    assert_eq!(flows, 2);
    assert!(code.contains("pub mod serial {"));
    assert!(code.contains("pub mod vga {"));
    assert!(code.contains("pub mod keyboard {"));
    assert!(code.contains("pub fn flow_boot()"));
    assert!(code.contains("pub fn flow_default()"));
}
